import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import ResponsiveNav from '../components/home/navbar/ResponsiveNav';
import Footer from '@/components/home/footer/footer';

const poppins = Poppins({
  weight: ['100', '300', '400', '500', '600', '700', '800', '900', '200'],
  subsets: ['latin'], // Especifica el subconjunto
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ResponsiveNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
